import { type RouteConfig, index, route } from "@react-router/dev/routes";

// Index route (home) and other app routes
export default [
	index("routes/home.tsx"),
	route("login", "routes/login.tsx"),
	route("dosen", "routes/dosen.tsx"),
	// Dosen-scoped sections
	route("dosen/nilai-presensi", "routes/dosen.nilai-presensi.tsx"),
	// Dosen: approve KRS pages
	route("dosen/approve-krs", "routes/dosen.approve-krs.tsx"),
	route("dosen/approve-krs/:nim", "routes/dosen.approve-krs.$nim.tsx"),
	route("dosen/input-presensi/:slug", "routes/dosen.input-presensi.$slug.tsx"),
	route("dosen/detail-presensi-ujian/:slug", "routes/dosen.detail-presensi-ujian.$slug.tsx"),
	route("dosen/presensi-pengawas/:slug", "routes/dosen.presensi-pengawas.$slug.tsx"),
	route("dosen/lihat-nilai/:code", "routes/dosen.lihat-nilai.$code.tsx"),
	route("dosen/set-komponen-nilai/:code", "routes/dosen.set-komponen-nilai.$code.tsx"),
	route("dosen/presensi/:slug", "routes/dosen.presensi.$slug.tsx"),
	route("dosen/list-presensi/:slug", "routes/dosen.list-presensi.$slug.tsx"),
	route("dosen/bimbingan-akademik", "routes/dosen.bimbingan-akademik.tsx"),
	route("dosen/ujian", "routes/dosen.ujian.tsx"),
	route("dosen/ujian-pendadaran", "routes/dosen.ujian-pendadaran.tsx"),
	route("dosen/bimbingan", "routes/dosen.bimbingan.tsx"),
	route("dosen/detail-ta/:nim", "routes/dosen.detail-ta.$nim.tsx"),
	route("dosen/log-bimbingan/:nim", "routes/dosen.log-bimbingan.$nim.tsx"),
	route("dosen/kelola-rps", "routes/dosen.kelola-rps.tsx"),
	route("dosen/profile", "routes/dosen.profile.tsx"),
	route("dosen/edit-profile", "routes/dosen.edit-profile.tsx"),
	route("nilai-presensi", "routes/nilai-presensi.tsx"),
	route("ujian", "routes/ujian.tsx"),
	route("presensi", "routes/presensi.tsx"),
	route("presensi/:id", "routes/presensi.$id.tsx"),
	route("schedule", "routes/schedule.tsx"),
	route("notifications", "routes/notifications.tsx"),
	route("notification/:id", "routes/notification.$id.tsx"),
	route("messages", "routes/messages.tsx"),
	route("chat/:id", "routes/chat.$id.tsx"),
	route("news/:id", "routes/news.$id.tsx"),
	route("news", "routes/news.tsx"),
	route("dosen/news", "routes/dosen.news.tsx"),
	route("announcements/:id", "routes/announcement.$id.tsx"),
	route("pembayaran", "routes/pembayaran.tsx"),
	route("pembayaran/:id", "routes/pembayaran.$id.tsx"),
	route("detail-pembayaran", "routes/detail-pembayaran.tsx"),
	route("pay-now", "routes/pay-now.tsx"),
	route("select-payment", "routes/select-payment.tsx"),
	route("confirm-payment", "routes/confirm-payment.tsx"),
	route("krs-khs", "routes/krs-khs.tsx"),
	route("status-krs", "routes/status-krs.tsx"),
	route("profile", "routes/profile.tsx"),
	route("edit-profile", "routes/edit-profile.tsx"),
	route("pengajuan", "routes/pengajuan.tsx"),
	route("log-bimbingan", "routes/log-bimbingan.tsx"),
	route("dev", "routes/dev.tsx"),
] satisfies RouteConfig;
